a=float(input('enter value of a ='))
b=float(input('enter value of b ='))
c=float(input('enter value of c ='))
d=float(input('enter value of d ='))
c=(a*b)/(c+d)
print('-'*50)
print('value of a =',a)
print('value of b =',b)
print('value of c =',c)
print('value of d =',d)
