l=float(input('length of rectangle(L)='))
b=float(input('Breadth of rectangle(B)='))
print('-'*30)
perimeter=2*(l+b)
print('length(l)  =',l)
print('breadth(b) =',b)
print('-'*30)
print('perimeter(p)=',perimeter)
print('-'*30)
